version: "3.4"
services:

  frontend:
    image: "tranvutuan2001/frontend"
    stdin_open: true

  backend:
    image: "tranvutuan2001/backend"

  keycloak:
    image: "jboss/keycloak"
    environment:
      - KEYCLOAK_USER=well
      - KEYCLOAK_PASSWORD=whale
      - KEYCLOAK_IMPORT=/tmp/realm-export.json
      - KEYCLOAK_FRONTEND_URL=http://localhost/keycloak
    volumes:
      - ./realm-export.json:/tmp/realm-export.json
      - ./register.ftl:/opt/jboss/keycloak/themes/base/login/register.ftl

  mongo_db:
    image: "mongo:4.2-bionic"
    ports:
      - "27017:27017"

  mongo_db_web_interface:
    image: "mongo-express"
    ports:
      - "4000:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo_db

  nginx:
    image: "nginx:1.18.0-alpine"
    ports:
      - 80:80
    volumes:
      - ./nginx.conf.dev:/etc/nginx/conf.d/default.conf