version: "3.4"
services:

  frontend:
    build: ./frontend
    stdin_open: true
    restart: always

  backend:
    build: ./backend
    restart: always

  keycloak:
    image: "jboss/keycloak"
    restart: always
    environment:
      - KEYCLOAK_USER=well
      - KEYCLOAK_PASSWORD=whale
      - KEYCLOAK_IMPORT=/tmp/realm-export.json
      - KEYCLOAK_FRONTEND_URL=http://qdog.ml/keycloak
    volumes:
      - ./realm-export.json:/tmp/realm-export.json
      - ./register.ftl:/opt/jboss/keycloak/themes/base/login/register.ftl

  mongo_db:
    image: "mongo:4.2-bionic"
    restart: always
    ports:
      - "27017:27017"

  nginx:
    image: "nginx:1.18.0-alpine"
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf